### ISSUE TITLE
What is the concept of applyGate()?

### ISSUE THREAD

**Issue by devildonkey1392** [cda-tum/qcec#35]
Hi,

I can't understand the concept of function _applyGate_ from the code and paper.

Can you explain it more?

Thanks for your help.

**Comment by burgholzer** [comment]
Hi,

let's look at it. The goal is to apply an operation to the current state of the system, i.e.,  `to`.
Now this can either be a decision diagram representing a vector (in case of simulation) or a matrix (in case of the other checker).
The important part happens here:
https://github.com/cda-tum/qcec/blob/10b8d14b3c40e44cfc9d114571d9be6670fc4b63/include/EquivalenceChecker.hpp#L119-L128

 - For vectors, it is straightforward: Obtain the decision diagram for the operation to be applied (`op->getDD(dd, permutation)`) accounting for the currently tracked `permutation` of the qubits and then conduct the conceptual matrix-vector multiplication `to = dd->multiply(<operation DD>, to)` to obtain the new state.
 - For matrices, another distinction is made whether the gate is applied "from the left" (`to = dd->multiply(op->getDD(dd, permutation), to);`) or, in an inverted fashion, "from the right" (`to = dd->multiply(to, op->getInverseDD(dd, permutation));`). This directly corresponds to the `G -> I <- G'` concept described in the *Advanced Equivalence Checking for Quantum Circuits* paper
 
 The rest of the function is just for reference counting which is needed for the underlying decision diagram package.

Maybe it helps to look at the version that is currently present in the `develop` branch, which makes things a little bit more straight-forward:
https://github.com/cda-tum/qcec/blob/72d3129d6e520c7cc4508d4d30b6b6fe561cac8b/include/checker/dd/TaskManager.hpp#L55-L71

Let me know if this clears things up a bit and don't hesitate to ask further questions!

**Comment by devildonkey1392** [comment]
Hi,

I want to ask more about the conceptual matrix-vector multiplication in decision diagram.

Can you explain the function _dd->multiply()_?

Thanks a lot!

**Comment by burgholzer** [comment]
Assume you are given a decision diagram that represents a matrix (e.g., the matrix of a Hadamard operation) and a decision diagram that represents a vector (e.g., the current state vector of the system).
Then, conceptually, `dd->multiply(<qc::MatrixDD>, <qc::VectorDD>)` merely performs the respective matrix-vector multiplication `M * v`.

If you want to learn more on how the multiplication of decision diagram works, have a look at the [Advanced Simulation of Quantum Computations](https://iic.jku.at/files/eda/2018_tcad_advanced_simulation_quantum_computations.pdf) paper, in particular page 7.

**Comment by devildonkey1392** [comment]
Hi,

I get it.

Thanks for your help.
